### ISSUE TITLE
is this project abandoned?

### ISSUE THREAD

**Issue by gnzsnz** [ranaroussi/pystore#73]
just asking

**Comment by steelep** [comment]
feels like it, honestly just better off implementing most of this stuff yourself, its not hard.

**Comment by yohplala** [comment]
Hi, I implemented this kind of datastore service [here](https://github.com/yohplala/oups), named "oups", during spare time, as a requirement for another private project.
Development of "oups" is not a "strong" priority either (it does most of what I need - I have a few items planned, but they will come when it is time), but if you are interested and encounter any bug, I will be interested in looking at it.
All tests are running and I take care of that for each new feature.
The failing CI is due to documentation, that I have not taken time to solve, since months...

**Comment by gnzsnz** [comment]
based on the replies there is interest
